### ISSUE TITLE
Clamp can go in Helm 

### ISSUE THREAD

**Issue by kasbah** [niilohlin/helm-extras#1]
http://package.elm-lang.org/packages/elm-lang/core/1.0.0/Basics#clamp

**Comment by kasbah** [comment]
No comment?

**Comment by niilohlin** [comment]
Oh, sorry. But clamp is already in helm-extras. I'm new to collaborating. Should I have done something else?

**Comment by kasbah** [comment]
:)

I just meant we should put it in helm, not helm-extras. Maybe it should be a bug on helm.
