### ISSUE TITLE
Rescue Animation and Transition

### ISSUE THREAD

**Issue by kasbah** [niilohlin/helm-extras#2]
These were removed for 0.7. Have a look at 0.6.

https://github.com/switchface/helm/tree/942e2a9c5abf540a18983728e0188f1ee68b4a19/src/FRP/Helm

**Comment by niilohlin** [comment]
Fixed in commit https://github.com/niilohlin/helm-extras/commit/bcda3c18a3ca70fc8f84a7599daf392d112c4f1f

**Comment by kasbah** [comment]
Will these actually work with latest helm?

**Comment by niilohlin** [comment]
It now works with the latest helm.
